name: tourze
version: 1
handle:
- rewrite: if (!is_dir() && !is_file()) goto "index.php%{REQUEST_URI}"
- compress:  if ( out_header["Content-type"] ~ "text/css" ) compress
- compress:  if ( out_header["Content-type"] ~ "text/javascript" ) compress
- compress:  if ( out_header["Content-type"] ~ "application/pdf" ) compress
- compress:  if ( out_header["Content-type"] ~ "application/vnd.ms-excel" ) compress
- compress:  if ( out_header["Content-type"] ~ "application/vnd.ms-powerpoint" ) compress
- compress:  if ( out_header["Content-type"] ~ "image/jpeg" ) compress
- compress:  if ( out_header["Content-type"] ~ "image/png" ) compress
- compress:  if ( out_header["Content-type"] ~ "image/gif" ) compress
- compress:  if ( out_header["Content-type"] ~ "image/gif" ) compress
